# Generated by Django 4.2.3 on 2023-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbucket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bucket',
            name='desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucket',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
